name: BlazinFly
main: iiFlamiinBlaze\BlazinFly\BlazinFly
description: An advanced survival fly plugin!
version: 1.8.3
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: iiFlamiinBlaze
load: POSTWORLD
commands:
  fly:
    description: "Command which allows flight when in Survival Mode!"
permissions:
  fly.command:
    description: "BlazinFly command permission"
    default: op