name: BlazinFly
main: iiFlamiinBlaze\BlazinFly\BlazinFly
description: An advanced survival fly plugin!
version: 1.8.6
api: 3.0.0
author: iiFlamiinBlaze
commands:
  fly:
    description: "Command which allows flight when in Survival Mode!"
permissions:
  fly.command:
    description: "BlazinFly command permission"
    default: op
  fly.other:
    description: "Allow you to activate fly for other players"
    default: op