name: BlazinFly
main: iiFlamiinBlaze\BlazinFly\BlazinFly
description: An advanced survival fly plugin!
version: 1.9.0
api: 4.0.0
author: iiFlamiinBlaze
commands:
  fly:
    permission: "blazinfly.command"
    description: "Command which allows flight when in Survival Mode!"
permissions:
  blazinfly.command:
    description: "BlazinFly command permission"
    default: op
  blazinfly.other:
    description: "Allow you to activate fly for other players"
    default: op